### ISSUE TITLE
Does `token.verify()` still work as expected?

### ISSUE THREAD

**Issue by 4kimov** [AscendingCreations/AxumCSRF#11]
Sorry for the general question. Looks like `0.8.0` has just been released. I've been trying to debug for the longest time why verifying a token keeps returning `Err(Verify)` for me. Is it possible that something in the lib has changed? I seem to be following the examples.

**Comment by genusistimelord** [comment]
I ran it a few time already and it seems to be working 100% fine? I ran this via the minimal test. 

The token hashing has changed from argon2 to hmac with sha256. which is to help prevent Dos attacks while still offering adequate protections. So if you are trying to use a long term Token that was before the update this will no longer work.

**Comment by 4kimov** [comment]
Ok, thank you for checking. Must be something on my end. I'll close the issue, just wanted to confirm I'm not missing anything. Appreciate it.

**Comment by genusistimelord** [comment]
feel free to post the code that is failing I can always take a look too.
