### ISSUE TITLE
Docs say axum 0.7 is supported, but Cargo.toml lists 0.6.12 as a dev dependencies

### ISSUE THREAD

**Issue by avtrujillo** [AscendingCreations/AxumCSRF#14]
I'm not really sure in what context it's being used as a dev-dependency, since the examples seem to be using 0.7.1 and I don't see any tests

**Comment by genusistimelord** [comment]
I mostly Ran tests by running the 2 examples. I will remove those dev-dependency as yes those would confuse people.

**Comment by genusistimelord** [comment]
I have removed them within [68da974bacc31f2c2c0524524b5fe9eb9e86503f ](https://github.com/AscendingCreations/AxumCSRF/commit/68da974bacc31f2c2c0524524b5fe9eb9e86503f)

I really should get some tests in, but they are a pain to get setup.
