### ISSUE TITLE
Please add a way to omit lifespan for 'session' only cookie

### ISSUE THREAD

**Issue by adayoung** [AscendingCreations/AxumCSRF#18]
Hi! This is a lovely crate and I was able to use it with little effort despite being very new to rust. I was looking for a way to omit the lifespan field in the config but it looks like it picks up a default of 6 hours and there's no way to have a session-only cookie with it. Can you please add a way to omit the lifetime configuration field? Thank you!

**Comment by genusistimelord** [comment]
Hello and thank you for using my Crates. 

By Session-only cookie you mean to Store the CSRF inside an axum_session Session to Prevent Post Replay Attacks?

I would mostly Make sure the CSRF Cookie lives a long enough lifetime to meet security standards. As we don't want to Store this cookie or use this cookie in the long term. It is more to ensure during a Login or register that the Contents were not modified or Adjusted by some 3rd party user. Hence man in the middle attack. If you Reuse the CSRF cookie for long term duration you Risk someone in the middle being able to Tamper with it sooner or later and the contents of the page or requests along with it.  You can increase the Lifespan of the cookie by configuring it in the config to live longer. I just don't recommend it.

So maybe if you could Explain the purpose of what your attempting to do so we can see what could be done.

**Comment by adayoung** [comment]
Oh, no no. By session-only cookie I meant a cookie without any Expires or Max-Age attribute.

MDN explains it better here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#removal_defining_the_lifetime_of_a_cookie
> Session cookies — cookies without a Max-Age or Expires attribute – are deleted when the current session ends. The browser defines when the "current session" ends, and some browsers use session restoring when restarting. This can cause session cookies to last indefinitely.

Is that a bad idea? They do that in [gorilla-csrf](https://github.com/gorilla/csrf) if the lifetime in configuration is set to 0. Let me open a pull request!

**Comment by genusistimelord** [comment]
I accepted your PR. though As a side note a long life Session makes CSRF Less Secure. To keep it as Secure as possible even with a long lived Session I would suggest Regenerating the CSRF every so often in terms of a Webpage that might be a Client like App instead of a Get and Post style Site.

At the moment we have no way to force regeneration yet but that can be added.

**Comment by adayoung** [comment]
Yay thank you! Session cookies are usually cleaned out in practice when people close their browser. I agree a long lived session can be risky and some people just never ever close their browser for what it's worth. The default value of 6 hours is really good!

I think forcing a regeneration would likely involve actually remembering stuff on the server side which sounds like all kinds of complicated right now. Let me get back if I get any ideas! Thank you again for this crate!
