### ISSUE TITLE
example does not compile

### ISSUE THREAD

**Issue by amkhlv** [AscendingCreations/AxumCSRF#7]
error[E0599]: no method named `into_make_service` found for struct `Router<CsrfConfig, _>` in the current scope

**Comment by genusistimelord** [comment]
ahh Ill update the Example to the newest Axum.

**Comment by genusistimelord** [comment]
I updated the Example it should use the new way.

**Comment by amkhlv** [comment]
It seems that   `into_make_service()` is only defined on `Router<(), _>` while here we have `Router<CsrfConfig, _>`

**Comment by genusistimelord** [comment]
hmm it should just take CSRFConfig just fine. I am wondering if the error is from somewhere else. as sometimes Axum errors dont always Tell you what the real issue is. 

You can try to make a State Struct instead like


```
use axum::extract::FromRef;

#[derive(Clone)]
pub struct SystemState {
   pub csrf: axum_csrf::CsrfConfig,
}

impl SystemState {
    pub fn new(
        csrf: axum_csrf::CsrfConfig,
    ) -> Self {
        Self {
            csrf,
        }
    }
}

impl FromRef<SystemState> for axum_csrf::CsrfConfig {
    fn from_ref(input: &SystemState) -> Self {
        input.csrf.clone()
    }
}


```

**Comment by genusistimelord** [comment]
I inserted a Full Example rather than a Partial and included a working example in the new Example folder. IF you continue to have issues with the router returning an Error you may need to insert Axum Debug macros above each function to figure out which one is not correct.

**Comment by amkhlv** [comment]
It seems that   `into_make_service()` is only defined on `Router<(), _>` while here we have `Router<CsrfConfig, _>`

**Comment by amkhlv** [comment]
I got it. The thing is, `.with_state(...)` should go the last in the chains, after all `.route(...)`s . Precisely as in your example. I thought it would not matter... Now it all works. Thank you !
